## JMS
spring:
  jms:
    template:
      default-destination: tacocloud.order.queue

  artemis:
    host: artemis.tacocloud.com
    port: 61617
    user: tacoweb
    password: l3tm31n

---
spring:
  profiles: production
  activemq:
    broker-url: tcp://activemq.tacocloud.com
    user: tacoweb
    password: l3tm31n
